import enum

from sqlalchemy import Enum


class WorkspaceRole(enum.StrEnum):
    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"
    GUEST = "guest"


class UploadStatus(enum.StrEnum):
    PENDING = "pending"
    READY = "ready"
    REJECTED = "rejected"


class AuthTokenPurpose(enum.StrEnum):
    VERIFY_EMAIL = "verify_email"
    RESET_PASSWORD = "reset_password"  # noqa: S105  (a purpose label, not a credential)


class ShareAccessOutcome(enum.StrEnum):
    OK = "ok"
    BAD_PASSWORD = "bad_password"  # noqa: S105  (an outcome label, not a credential)
    EXPIRED = "expired"
    REVOKED = "revoked"


def db_enum(enum_cls: type[enum.Enum], name: str) -> Enum:
    """Stored as VARCHAR plus a named CHECK constraint, not a native PostgreSQL enum type.

    Native enum types are created with their table but never dropped by an autogenerated
    downgrade, and one type shared by two tables makes create_table run CREATE TYPE twice.
    A CHECK constraint has neither problem. Members are stored by value.
    """
    return Enum(
        enum_cls,
        name=name,
        native_enum=False,
        create_constraint=True,
        values_callable=lambda e: [m.value for m in e],
    )
