"""Model metadata checks. No database is needed: everything is inspected or compiled offline.

These guard the rule that revisions are only ever produced by `alembic revision --autogenerate`:
if a model uses something autogenerate cannot create correctly, a test here should fail first.
"""

import re
import warnings

import pytest
from sqlalchemy import Enum, String, Table
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

import app.models  # noqa: F401  (registers every model on Base.metadata)
from app.core.ids import ID_LENGTH, generate_random_id
from app.db.base import Base

EXPECTED_TABLES = {
    "users",
    "workspaces",
    "workspace_members",
    "workspace_invites",
    "workspace_invite_folders",
    "folders",
    "folder_grants",
    "documents",
    "document_versions",
    "share_links",
    "share_link_access_logs",
    "activity_logs",
}
# tables that were deliberately removed from the design
REMOVED_TABLES = {"auth_tokens"}


def tables() -> list[Table]:
    return list(Base.metadata.sorted_tables)


def test_all_expected_tables_are_registered() -> None:
    names = {t.name for t in tables()}
    assert names == EXPECTED_TABLES
    assert not names & REMOVED_TABLES


@pytest.mark.parametrize("table", tables(), ids=lambda t: t.name)
def test_every_table_inherits_both_mixins(table: Table) -> None:
    id_col = table.c["id"]
    assert id_col.primary_key
    assert isinstance(id_col.type, String) and id_col.type.length == ID_LENGTH
    assert [c.name for c in table.primary_key.columns] == ["id"]
    for name in ("created_at", "updated_at"):
        col = table.c[name]
        assert not col.nullable
        assert col.server_default is not None
    # mixin columns are ordered: id first, timestamps last
    names = [c.name for c in table.columns]
    assert names[0] == "id"
    assert names[-2:] == ["created_at", "updated_at"]


def test_removed_columns_are_absent() -> None:
    assert "email_verified_at" not in Base.metadata.tables["users"].c
    # the current version is the latest version_number; there is no back-reference column
    assert "current_version_id" not in Base.metadata.tables["documents"].c
    assert "storage_key" not in Base.metadata.tables["documents"].c
    assert "storage_key" in Base.metadata.tables["document_versions"].c
    assert "storage_url" in Base.metadata.tables["document_versions"].c


def test_random_id_format_and_uniqueness() -> None:
    ids = {generate_random_id() for _ in range(20_000)}
    assert len(ids) == 20_000
    for value in list(ids)[:2_000]:
        assert re.fullmatch(r"[A-Za-z][0-9A-Za-z]{11}", value)


def test_all_foreign_keys_resolve_to_existing_columns() -> None:
    for table in tables():
        for fk in table.foreign_keys:
            assert fk.column is not None, f"{table.name}: unresolved FK {fk}"


def test_constraint_naming_convention_is_applied() -> None:
    users = Base.metadata.tables["users"]
    assert users.primary_key.name == "pk_users"
    workspaces = Base.metadata.tables["workspaces"]
    fk_names = {fk.constraint.name for fk in workspaces.foreign_keys if fk.constraint is not None}
    assert fk_names == {"fk_workspaces_owner_id_users"}


def enum_columns() -> list[tuple[str, str, Enum]]:
    return [
        (t.name, c.name, c.type) for t in tables() for c in t.columns if isinstance(c.type, Enum)
    ]


def test_enums_hold_the_design_values() -> None:
    found = {(t, c): e.enums for t, c, e in enum_columns()}
    assert found == {
        ("workspace_members", "role"): ["owner", "admin", "member", "guest"],
        ("document_versions", "upload_status"): ["pending", "ready", "rejected"],
        ("share_link_access_logs", "outcome"): ["ok", "bad_password", "expired", "revoked"],
    }


def test_enums_are_varchar_with_check_not_native_types() -> None:
    """Native enum types are never dropped by an autogenerated downgrade and break when shared."""
    assert enum_columns()
    for table, column, enum_type in enum_columns():
        assert enum_type.native_enum is False, f"{table}.{column} is a native enum"
        assert enum_type.create_constraint is True, f"{table}.{column} has no CHECK constraint"


def test_metadata_has_no_circular_foreign_keys() -> None:
    """Autogenerate cannot create a circular FK: Alembic drops use_alter constraints."""
    with warnings.catch_warnings():
        warnings.simplefilter("error")  # SQLAlchemy warns when tables cannot be sorted
        assert len(Base.metadata.sorted_tables) == len(EXPECTED_TABLES)
    for table in tables():
        for constraint in table.foreign_key_constraints:
            assert not constraint.use_alter, f"{table.name}.{constraint.name} uses use_alter"


def compiled_table_ddl() -> dict[str, str]:
    dialect = postgresql.dialect()  # type: ignore[no-untyped-call]
    return {t.name: str(CreateTable(t).compile(dialect=dialect)) for t in tables()}


def test_every_foreign_key_is_created_inline() -> None:
    """A constraint missing from CREATE TABLE would silently not exist after an upgrade."""
    for table in tables():
        ddl = compiled_table_ddl()[table.name]
        assert ddl.count("FOREIGN KEY") == len(table.foreign_key_constraints), table.name


def compiled_ddl() -> dict[str, str]:
    dialect = postgresql.dialect()  # type: ignore[no-untyped-call]
    out: dict[str, str] = {}
    for table in tables():
        parts = [str(CreateTable(table).compile(dialect=dialect))]
        parts += [str(CreateIndex(ix).compile(dialect=dialect)) for ix in table.indexes]
        out[table.name] = "\n".join(parts)
    return out


def test_ddl_compiles_for_postgresql_with_expected_indexes() -> None:
    ddl = compiled_ddl()
    assert set(ddl) == EXPECTED_TABLES
    # partial unique index enforcing a single owner per workspace
    assert "WHERE role = 'owner'" in ddl["workspace_members"]
    # duplicate pending invites are blocked
    assert "accepted_at IS NULL AND revoked_at IS NULL" in ddl["workspace_invites"]
    # sibling folder names: case-insensitive, NULLS NOT DISTINCT, live rows only
    assert "NULLS NOT DISTINCT" in ddl["folders"]
    assert "lower(name)" in ddl["folders"]
    # case-insensitive unique email without the citext extension
    assert "lower(email)" in ddl["users"]
    # composite foreign keys with cascading revocation
    assert (
        "FOREIGN KEY(workspace_id, user_id) REFERENCES workspace_members (workspace_id, user_id)"
        in ddl["folder_grants"]
    )
    assert "ON DELETE CASCADE" in ddl["folder_grants"]
    # enums are VARCHAR + CHECK
    assert "CHECK (role IN ('owner', 'admin', 'member', 'guest'))" in ddl["workspace_members"]
    assert "CHECK (upload_status IN ('pending', 'ready', 'rejected'))" in ddl["document_versions"]
    # JSONB / INET
    assert "JSONB" in ddl["activity_logs"]
    assert "INET" in ddl["share_link_access_logs"]


def test_no_database_extension_type_or_function_is_required() -> None:
    """Autogenerate must be self-sufficient: no citext, no native enum, no DB function defaults."""
    for name, ddl in compiled_ddl().items():
        assert "CITEXT" not in ddl.upper(), name
        assert "random_id" not in ddl, name
        assert "CREATE TYPE" not in ddl.upper(), name
