"""guest document grants replace folder grants

Revision ID: 6acf875ce63a
Revises: 6acac0e2383a
Create Date: 2026-09-22 15:24:05.980528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6acf875ce63a"
down_revision: Union[str, Sequence[str], None] = "6acac0e2383a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # reordered by hand: document_grants' composite FK needs this constraint to exist first
    op.create_unique_constraint("uq_documents_id_workspace_id", "documents", ["id", "workspace_id"])
    op.create_table(
        "document_grants",
        sa.Column("id", sa.String(length=12), nullable=False),
        sa.Column("workspace_id", sa.String(length=12), nullable=False),
        sa.Column("document_id", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.String(length=12), nullable=False),
        sa.Column("granted_by", sa.String(length=12), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "workspace_id"],
            ["documents.id", "documents.workspace_id"],
            name="fk_document_grants_document_id_documents",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_document_grants_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_members.workspace_id", "workspace_members.user_id"],
            name="fk_document_grants_workspace_id_workspace_members",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_grants")),
        sa.UniqueConstraint(
            "document_id", "user_id", name="uq_document_grants_document_id_user_id"
        ),
    )
    op.create_index(
        "ix_document_grants_workspace_id_user_id",
        "document_grants",
        ["workspace_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "workspace_invite_documents",
        sa.Column("id", sa.String(length=12), nullable=False),
        sa.Column("invite_id", sa.String(length=12), nullable=False),
        sa.Column("document_id", sa.String(length=12), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_workspace_invite_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["workspace_invites.id"],
            name=op.f("fk_workspace_invite_documents_invite_id_workspace_invites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_invite_documents")),
        sa.UniqueConstraint(
            "invite_id", "document_id", name="uq_workspace_invite_documents_invite_id_document_id"
        ),
    )
    op.create_index(
        op.f("ix_workspace_invite_documents_document_id"),
        "workspace_invite_documents",
        ["document_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_workspace_invite_folders_folder_id"), table_name="workspace_invite_folders"
    )
    op.drop_table("workspace_invite_folders")
    op.drop_index(op.f("ix_folder_grants_workspace_id_user_id"), table_name="folder_grants")
    op.drop_table("folder_grants")
    op.drop_constraint(op.f("uq_folders_id_workspace_id"), "folders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_folders_id_workspace_id"),
        "folders",
        ["id", "workspace_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_table(
        "folder_grants",
        sa.Column("id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("workspace_id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("folder_id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("granted_by", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id", "workspace_id"],
            ["folders.id", "folders.workspace_id"],
            name=op.f("fk_folder_grants_folder_id_folders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_folder_grants_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_members.workspace_id", "workspace_members.user_id"],
            name=op.f("fk_folder_grants_workspace_id_workspace_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folder_grants")),
        sa.UniqueConstraint(
            "folder_id",
            "user_id",
            name=op.f("uq_folder_grants_folder_id_user_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_folder_grants_workspace_id_user_id"),
        "folder_grants",
        ["workspace_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "workspace_invite_folders",
        sa.Column("id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("invite_id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("folder_id", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name=op.f("fk_workspace_invite_folders_folder_id_folders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["workspace_invites.id"],
            name=op.f("fk_workspace_invite_folders_invite_id_workspace_invites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_invite_folders")),
        sa.UniqueConstraint(
            "invite_id",
            "folder_id",
            name=op.f("uq_workspace_invite_folders_invite_id_folder_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_workspace_invite_folders_folder_id"),
        "workspace_invite_folders",
        ["folder_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_workspace_invite_documents_document_id"), table_name="workspace_invite_documents"
    )
    op.drop_table("workspace_invite_documents")
    op.drop_index("ix_document_grants_workspace_id_user_id", table_name="document_grants")
    op.drop_table("document_grants")
    op.drop_constraint("uq_documents_id_workspace_id", "documents", type_="unique")
    # ### end Alembic commands ###
