"""initial revision

Revision ID: bba684a776e9
Revises: 
Create Date: 2026-09-20 04:52:46.703161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bba684a776e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 200', name=op.f('ck_users_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 200', name=op.f('ck_workspaces_name_length')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=True),
    sa.Column('actor_id', sa.String(length=12), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.String(length=12), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_activity_logs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index('ix_activity_logs_workspace_id_created_at', 'activity_logs', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=True),
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("length(name) BETWEEN 1 AND 255 AND name !~ '[/\\\\]'", name=op.f('ck_folders_name_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_folders_owner_id_users')),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], name=op.f('fk_folders_parent_folder_id_folders')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_folders_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_folders_id_workspace_id')
    )
    op.create_index(op.f('ix_folders_parent_folder_id'), 'folders', ['parent_folder_id'], unique=False)
    op.create_index('ix_folders_personal_owner_id', 'folders', ['owner_id'], unique=False, postgresql_where=sa.text('workspace_id IS NULL'))
    op.create_index('ix_folders_workspace_id_parent_folder_id', 'folders', ['workspace_id', 'parent_folder_id'], unique=False)
    op.create_index('uq_folders_sibling_name_personal', 'folders', ['owner_id', 'parent_folder_id', sa.literal_column('lower(name)')], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL AND workspace_id IS NULL'))
    op.create_index('uq_folders_sibling_name_workspace', 'folders', ['workspace_id', 'parent_folder_id', sa.literal_column('lower(name)')], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL AND workspace_id IS NOT NULL'))
    op.create_table('workspace_invites',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member', 'guest')", name=op.f('ck_workspace_invites_role_not_owner')),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_workspace_invites_token_hash_format')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_invites_invited_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invites_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_workspace_invites_token_hash'))
    )
    op.create_index(op.f('ix_workspace_invites_workspace_id'), 'workspace_invites', ['workspace_id'], unique=False)
    op.create_index('uq_workspace_invites_pending', 'workspace_invites', ['workspace_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'guest', name='workspace_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('invited_by', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_members_invited_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_workspace_id_user_id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index('uq_workspace_members_one_owner', 'workspace_members', ['workspace_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_table('documents',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=True),
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('folder_id', sa.String(length=12), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("length(filename) BETWEEN 1 AND 255 AND filename !~ '[/\\\\]'", name=op.f('ck_documents_filename_valid')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_documents_folder_id_folders')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_documents_owner_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_filename_lower', 'documents', [sa.literal_column('lower(filename)')], unique=False)
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index('ix_documents_personal_owner_id', 'documents', ['owner_id'], unique=False, postgresql_where=sa.text('workspace_id IS NULL'))
    op.create_index('ix_documents_workspace_id_folder_id_live', 'documents', ['workspace_id', 'folder_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('folder_grants',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.String(length=12), nullable=False),
    sa.Column('folder_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('granted_by', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id', 'workspace_id'], ['folders.id', 'folders.workspace_id'], name='fk_folder_grants_folder_id_folders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_folder_grants_granted_by_users')),
    sa.ForeignKeyConstraint(['workspace_id', 'user_id'], ['workspace_members.workspace_id', 'workspace_members.user_id'], name='fk_folder_grants_workspace_id_workspace_members', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folder_grants')),
    sa.UniqueConstraint('folder_id', 'user_id', name='uq_folder_grants_folder_id_user_id')
    )
    op.create_index('ix_folder_grants_workspace_id_user_id', 'folder_grants', ['workspace_id', 'user_id'], unique=False)
    op.create_table('workspace_invite_folders',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('invite_id', sa.String(length=12), nullable=False),
    sa.Column('folder_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_workspace_invite_folders_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['workspace_invites.id'], name=op.f('fk_workspace_invite_folders_invite_id_workspace_invites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invite_folders')),
    sa.UniqueConstraint('invite_id', 'folder_id', name='uq_workspace_invite_folders_invite_id_folder_id')
    )
    op.create_index(op.f('ix_workspace_invite_folders_folder_id'), 'workspace_invite_folders', ['folder_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('document_id', sa.String(length=12), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.Enum('pending', 'ready', 'rejected', name='upload_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('created_by', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("checksum_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_versions_checksum_sha256_format')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_document_versions_size_bytes_non_negative')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_document_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_versions_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_id_version_number'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_versions_storage_key')),
    sa.UniqueConstraint('storage_url', name=op.f('uq_document_versions_storage_url'))
    )
    op.create_table('share_links',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('document_id', sa.String(length=12), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=12), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_download', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_share_links_token_hash_format')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_share_links_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_share_links_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_links_token_hash'))
    )
    op.create_index(op.f('ix_share_links_document_id'), 'share_links', ['document_id'], unique=False)
    op.create_table('share_link_access_logs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('share_link_id', sa.String(length=12), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('ok', 'bad_password', 'expired', 'revoked', name='share_access_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], name=op.f('fk_share_link_access_logs_share_link_id_share_links')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_link_access_logs'))
    )
    op.create_index('ix_share_link_access_logs_share_link_id_accessed_at', 'share_link_access_logs', ['share_link_id', sa.literal_column('accessed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_share_link_access_logs_share_link_id_accessed_at', table_name='share_link_access_logs')
    op.drop_table('share_link_access_logs')
    op.drop_index(op.f('ix_share_links_document_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_workspace_invite_folders_folder_id'), table_name='workspace_invite_folders')
    op.drop_table('workspace_invite_folders')
    op.drop_index('ix_folder_grants_workspace_id_user_id', table_name='folder_grants')
    op.drop_table('folder_grants')
    op.drop_index('ix_documents_workspace_id_folder_id_live', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_documents_personal_owner_id', table_name='documents', postgresql_where=sa.text('workspace_id IS NULL'))
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_index('ix_documents_filename_lower', table_name='documents')
    op.drop_table('documents')
    op.drop_index('uq_workspace_members_one_owner', table_name='workspace_members', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('uq_workspace_invites_pending', table_name='workspace_invites', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_index(op.f('ix_workspace_invites_workspace_id'), table_name='workspace_invites')
    op.drop_table('workspace_invites')
    op.drop_index('uq_folders_sibling_name_workspace', table_name='folders', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL AND workspace_id IS NOT NULL'))
    op.drop_index('uq_folders_sibling_name_personal', table_name='folders', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL AND workspace_id IS NULL'))
    op.drop_index('ix_folders_workspace_id_parent_folder_id', table_name='folders')
    op.drop_index('ix_folders_personal_owner_id', table_name='folders', postgresql_where=sa.text('workspace_id IS NULL'))
    op.drop_index(op.f('ix_folders_parent_folder_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index('ix_activity_logs_workspace_id_created_at', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
